### ISSUE TITLE
Last Exception message when Discord is not launched

### ISSUE THREAD

**Issue by eltorrento** [Otakubuns/Sims4-DRP#1]
If you load the game first (before launching Discord) it will throw LE.
Steps:

0. Discord is not launched
1. Launch The Sims 4
2. Load the game and go to your households lot
3. Launch Discord

Problem:
After loading household lot it throws LE. Launching Discord does not restore Rich presence in this situation.

Expected:
No LE when Discord is not launched or after launching the game. Working RP after launching Discord while TS4 was launched as first.

[lastException.txt](https://github.com/Otakubuns/Sims4-DRP/files/11564878/lastException.txt)

**Comment by Otakubuns** [comment]
I never thought to test without Discord running(kinda dumb of me) so I have fixed this now.
I've only tested with minimal mods to fix it as quickly as possible so if you do get another issue please let me know.
Make sure you have Discord open before Sims 4 as it won't show the presence if you open it after.

Also tysm for using my mod! ❤️
