### ISSUE TITLE
Mod breaks time management after 1.103.250.1020/1.103.315.1020 patches (For Rent DLC)

### ISSUE THREAD

**Issue by eltorrento** [Otakubuns/Sims4-DRP#2]
After leaving build mode you are unable to use game time speed properly. 
Tested on both TS4 versions:
- 1.103.250.1020 (incl. For Rent DLC)
- 1.103.315.1020 (incl. For Rent DLC) - latest version

**Steps:**
1. Load the game and go to your households lot
2. Go to Build mode
3. Go to Live mode
4. Press, 1, 2 or 3 on your keyboard

**Problem:**
After going back to live mode from build mode "1,2,3" buttons stop working - only " ` " and "P" buttons allow you to pause/unpause game at normal speed but you are still unable to use fast speed and ultra speed. Same situation with UI using mouse.

**Expected:**
Time management (fast speed and ultra speed) should work in live mode after leaving build mode.

**Comment by Otakubuns** [comment]
Haven't touched this project in a bit but I am working on it. thank u for letting me know. It seems like the freezing issue was very easy but the backend the presence of updating is being buggy so it will be a bit to fix it.

**Comment by Otakubuns** [comment]
Ok, so everything is fixed and works. It should now be properly working. 
Thanks for letting me know and if there are any other issues please let me know! 
I did test it a ton but there's always a chance I could have missed something.
