### ISSUE TITLE
Recurent game freezes, lags & UI related issues

### ISSUE THREAD

**Issue by fasmer44** [Otakubuns/Sims4-DRP#6]
( Currently on Patch 1.110.311

https://github.com/user-attachments/assets/8005cb5d-ff8c-482c-9468-e3f9c3ddefcb

, Windows) 
Hello, thank you so much for all the hard work, i absolutely LOVE this mod & can't play without it...

I've tested in my save (which is not corrupted), I removed **_ALL_** of my other mods, except this one in particular...

I've ran into several glitches **WITH THIS MOD!!!!**, such as : 
1. Game freezes
2. Issues while dragging dishes in the trash can (via live mode)

_What exactly happens_ : 
Dragged a dish in the trash can, then the UI glitches & still has the dish icon preview **attached** to the cursor ; game freezes & I'm unable to play...

I've tried _**WITHOUT**_ the mod, it works completely fine, so I assume that it is from this mod, it can only be this.

Whenever you're able to, please update it to make it compatible with the latest patches, while fixing these issues, tysm for all you've done so far, I love this mod & I cannot play without it !

[SEE ATTACHEMENT FOR MORE INFO]

**Comment by Otakubuns** [comment]
Hi thanks so much for using this and I'm so happy you use it often!
I'm so sorry it's not working for you and causing issues. 

I've tested for about half an hour with the dishes and items in inventory specifically. I can't seem to replicate your issue with the dishes or moving items from the inventory. If there's anything you can let me know that might help(specs, how much CC you have in your game, if moving from build/buy, or if specific lots you've noticed).
I will look over the code since I am unsure if anything was changed in the newest EP but seeing as it's working all right without an update I will have to look into it further.

**Comment by fasmer44** [comment]
No problem, I love this mod so if it is a Mod related issue, I'd be glad to help!

I have installed no CC or other Mods when i first recorded the video, just this mod in particular..

I have no idea if it was my specs, I don't really have a powerful PC.. however, i've got a bunch of Mods next to this one & it runs perfectly, in Hi-Res, so I doubt that only this Mod makes my game lag, however I could be wrong, but I really doubt it...

There was also another glitch that i forgot to mention, but I'm not sure if it was from this Mod, but sometimes the game freezes as well when i try placing an object, it done that several times, but I am unable to say if it was from this Mod or not, but I'd like to let you aware still, just in case.

That would be awesome if you could be to see if there's anything wrong, sorry if that is a waste of your time btw!

**Comment by Otakubuns** [comment]
Oh no worries about "wasting my time" I'm happy to fix it if it's not working. 
I have an idea or workaround for what might be happening, once I make sure I iron out anything else it could be I will send the new ts4script and you can test it out.

**Comment by fasmer44** [comment]
you're amazing, thank you so so much!
i'd love to test it out once you release it, ty again!

**Comment by fasmer44** [comment]
my friends & i love this mod, can't wait to have this fix for them as well! <3

**Comment by Otakubuns** [comment]
I changed up a little of the reconnecting logic so if you get disconnected, you can now reconnect from the console with 'discord'.
I think the error with yours is that the connection is screwing up and constantly looping trying to reconnect. I may change it back to reconnecting and just having it try to reconnect every action but I don't wanna clog up the game with unnecessary calls. 
Lemme know your thoughts on that since I've been going back and forth between just having the reconnect command or just reconnecting on its own but it wouldn't have the same issue that your game was having as it won't loop until it connects.
You can try this file for now and lemme know if you are still having those issues, there's also a new discordRPC.log file that will be created wherever the .ts4script file is(just unzip it since github doesn't allow .ts4script for comment files).
So if it is having issues check that log to see if it logs any errors.

**Comment by fasmer44** [comment]
hello, ok so... i just installed the script file into my mods folder, at first it didn't work...

afterwards it worked & showed as intended in Discord, only worked for 'Browsing the Menu' though...

then, after launching my save, the detection stopped working... & it kept going back & forth with the original Activity layout of the game... i've cleared my cache on launch everytime, i restarted my pc... & even cleared Discord's cache several times, it didn't help, so I assume that it's another issue that needs to be fixed <3

I checked the discordRPC.log text file, it sent me this error several times in a row, Discord was running, no connectivity issues, even restarted it, it did not help as well ://///

![Not connected - error](https://github.com/user-attachments/assets/9ec93e63-c6d0-4d53-854d-95a7586d83c8)

**Comment by Otakubuns** [comment]
Alright thank you for trying it out, i'm going to keep with the original intention of having it check connection when setting presence, I've been testing it outside of Sims and I got more to do with it, the connection is corrupting some times and getting some weird errors so I will get back to you with any updates for that.

**Comment by fasmer44** [comment]
thank you so much!!!! 
actually, i gave the link to my friend to see if they could try it out... and it worked for them, so i assume that it's an issue on my end... but i don't know what it could be...

i'll try changing wifi to see if it shows up, i'll leave you another comment on here to let you know about how it goes <3

**Comment by Otakubuns** [comment]
That ts4script is not the final one so make sure you and your friend download my final one cause that one i sent you was very quickly done lol.
To troubleshoot your issue, you are using the Discord application correct? And if you are make sure to have it open before you have discord already open (for that ts4script atm). I'm unsure tho what could be blocking your connection, I'll look into that more.

**Comment by fasmer44** [comment]
no problem! i'll tell them, they'll update it right away once you release the final version!

and yes absolutely, i am using the application, not the PTB (Public Beta Testers) version, just the regular one.

i'm currently testing with another WiFi & will let you know in a couple of minutes.

**Comment by Otakubuns** [comment]
No worries, take your time. If you ctrl+shift+c for the console and type `discord` it will try to reconnect so i recommend trying that(put that in just to test it outside of updating automatically)

**Comment by Otakubuns** [comment]
Alright i think i settled on something that works and satisfying my want for reconnection. I've tested a decent amount and it doesn't make anymore extra connections to discord if it detects its not open, also the looping wont be a problem anymore.
Try this out and let me know how it goes:
[Otakubuns_Sims4DRP.zip](https://github.com/user-attachments/files/17926311/Otakubuns_Sims4DRP.zip)

**Comment by fasmer44** [comment]
thank you so much, trying this now!
i'll also test the console "trick" afterwards if it's not reconnecting, tyyy! <3

**Comment by Otakubuns** [comment]
i took out the console command for the newest one i sent u but i can for sure add it back on the main release, this one was more testing the automatic connection

**Comment by fasmer44** [comment]
i just launched my game, it works as expected so far, thank you for the quick fix!!!

& can't wait for the main release version :)) tysm for helping me you're amazing!!!

**Comment by fasmer44** [comment]
btw- i just tested in my game, and the issue with dragging the plates still appears to be lagging...

i don't know if it's on my end, it's definitely less worse than before, but there's _still_ a lag :/

**Comment by fasmer44** [comment]
correction : it is doing the same thing, it's as worse as before sadly..

**Comment by Otakubuns** [comment]
Hmm. I'm completely stumped on why that would be happening. 
My mod uses the same inject method a lot of other Sims mods use and the connection stuff should no longer loop. I'm so sorry that it's causing lag, is there anything logging or is the presence setting as normal?

**Comment by fasmer44** [comment]
![image](https://github.com/user-attachments/assets/2be19c39-6f96-49dc-9ab4-879194817052)

actually i checked and there's still errors, i have no idea if it's my WiFi or not, i changed it once again...

i'll try to change it back one last time to make sure that's it's not an issue on the mod itself.......

i'm unsure on what it could be :(((

**Comment by Otakubuns** [comment]
By your logging, you do have Discord open but it's somehow breaking, I will implement that Discord command again but it seems to be an issue on your network. I am going to change up one thing for your specific case though so ill give you a new ts4cript in a bit.

**Comment by fasmer44** [comment]
thank you!!! now the preview in discord no longer show up, i'm so sorry, i wish i could know how to fix it on my own, but except clearing caches, changing wifi & even restarting the game multiple times, nothing seems to be working, so i do not know what to do :/

**Comment by fasmer44** [comment]
hello, sorry for annoying you, i am back, & i'm relieved to say that it now works in discord & everything seems to be ok, i don't know what happened for it to work but it did :)))

**Comment by Otakubuns** [comment]
No worries! 
It sounds like there's a network issue with it connecting with discord, I would restart discord if you notice it. I will put in some sort of retry limit so that it doesn't spam your game which should stop that lag if it somehow breaks. Glad it's working though!

**Comment by Otakubuns** [comment]
Ok, about to release a new version with these changes implemented alongside a few other small things. Thank you for letting me know about those connection problems, also got me back into working on this again lol. ❤️

**Comment by fasmer44** [comment]
HIII!!! so sorry i'm late to this, but thank you so much for helping me, this has fixed everything & i am glad to see that you've been able to apply fixes to the mod after a few months without releasing another version, i love this mod & can't live without it <3

take care of yourself, tysm again 🩷
